version: 2

models:
  - name: interm_deals_stages_enriched
    description: "Enriched view of deal stages combining explicit stage changes and inferred activity-based stages."
    columns:
      - name: deal_id
        description: "Identifier of the deal."
        tests: [not_null]
      - name: stage
        description: "Numeric stage value derived from stage changes or inferred from activities or lost."
        tests: [not_null]
      - name: change_time
        description: "Timestamp of the stage change or activity due date."
        tests: [not_null]
      - name: lost_reason
        description: "Lost reason value when the change = lost; otherwise null."

  - name: interm_deals_times_users
    description: "Deal user change history and per deal minimal add_time."
    columns:
      - name: deal_id
        description: "Identifier of the deal."
        tests: [not_null]
      - name: user_id
        description: "User id assigned"
      - name: change_time
        description: "Timestamp of the user assignment change."
        tests: [not_null]
      - name: deal_add_time
        description: "Earliest `add_time` observed for the deal."
        tests: [not_null]

